### ISSUE TITLE
60 second timeout execute("ps", "x") in version 4.2

### ISSUE THREAD

**Issue by theangrydev** [dorkbox/SystemTray#181]
After upgrading to 4.2 I now see:

```
Exception in thread "display-tray-icon" java.lang.NoSuchMethodError: com.sun.jna.NativeLibrary.close()V
	at dorkbox.jna.linux.GtkLoader.<clinit>(GtkLoader.java:174)
	at dorkbox.jna.linux.GtkEventDispatch.startGui(GtkEventDispatch.java:80)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:651)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:171)
```

I was able to make it work by excluding:
```
<dependency>
    <groupId>com.dorkbox</groupId>
    <artifactId>SystemTray</artifactId>
    <version>4.2</version>
    <exclusions>
        <exclusion>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-jpms</artifactId>
        </exclusion>
        <exclusion>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform-jpms</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

And adding:
```
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna-jpms</artifactId>
    <artifactId>jna</artifactId>
    <version>5.12.1</version>
</dependency>
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna-platform-jpms</artifactId>
    <artifactId>jna-platform</artifactId>
    <version>5.12.1</version>
</dependency>
```

I think this might be because I am using Java 8 (and I can't upgrade past that for now).

Perhaps you could distribute:
- a `SystemTray` artifact using `jna`and `jna-platform` 
- a `SystemTray-jpms` artifact using `jna-jpms`and `jna-platform-jpms` 

I also seem to be seeing a 2x performance hit versus version 3.17, I'll raise another issue when I have time to dig into that with what I am seeing

**Comment by pietrygamat** [comment]
Are you sure you are not including jna in some different version transitively by one of your other dependencies? This version seems to work well on java 8 without any such modifications for me.

**Comment by theangrydev** [comment]
@pietrygamat I use `maven-enforcer-plugin` with `<dependencyConvergence/>`and `<requireUpperBoundDeps/>` to ensure only the intended version of dependencies is included, so I don't think that is my issue

I'm using Java version:
```
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.352-b08, mixed mode)

```

**Comment by dorkbox** [comment]
Can you tell me more about the box it's running on? You can enable `DEBUG` to output loads of info that helps me run a similar env to track down errors.

**Comment by theangrydev** [comment]
Here are some logs running with the original jpms JARs on the classpath, and the non-jpms JARs absent.

It does eventually start up after ~60 seconds, I must have been too impatient when testing last time.

So the issue is that it is a very slow startup, but does seem functional when it has started.

It looks like there is a 60 second timeout occuring perhaps, between 
```
2023-01-19 00:51:40,777 DEBUG main Prefer GTK3: true
----------------------------------------------------------------------
2023-01-19 00:52:40,820 DEBUG main Currently using the 'Gnome' desktop environment
```

Full logs:
```
----------------------------------------------------------------------
2023-01-19 00:51:40,726 INFO  main Starting system tray...
----------------------------------------------------------------------
2023-01-19 00:51:40,728 DEBUG main Version 4.2
----------------------------------------------------------------------
2023-01-19 00:51:40,728 DEBUG main OS: Linux
----------------------------------------------------------------------
2023-01-19 00:51:40,728 DEBUG main Arch: amd64
----------------------------------------------------------------------
2023-01-19 00:51:40,728 DEBUG main Oracle Corporation OpenJDK 64-Bit Server VM 1.8.0_352
----------------------------------------------------------------------
2023-01-19 00:51:40,728 DEBUG main JPMS enabled: false
----------------------------------------------------------------------
2023-01-19 00:51:40,728 DEBUG main Is Auto sizing tray/menu? true
----------------------------------------------------------------------
2023-01-19 00:51:40,728 DEBUG main Is JavaFX detected? false
----------------------------------------------------------------------
2023-01-19 00:51:40,728 DEBUG main Is SWT detected? false
----------------------------------------------------------------------
2023-01-19 00:51:40,777 DEBUG main Java Swing L&F: Metal
----------------------------------------------------------------------
2023-01-19 00:51:40,777 DEBUG main Auto-detecting tray type
----------------------------------------------------------------------
2023-01-19 00:51:40,777 DEBUG main Force GTK2: false
----------------------------------------------------------------------
2023-01-19 00:51:40,777 DEBUG main Prefer GTK3: true
----------------------------------------------------------------------
2023-01-19 00:52:40,820 DEBUG main Currently using the 'Gnome' desktop environment
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

----------------------------------------------------------------------
2023-01-19 00:52:40,821 DEBUG main Currently using the 'ubuntu' session type
----------------------------------------------------------------------
2023-01-19 00:52:40,996 DEBUG main GTK: libgtk-3.so.0
----------------------------------------------------------------------
2023-01-19 00:52:40,998 DEBUG GTK Native Event Loop Running GTK Native Event Loop
----------------------------------------------------------------------
2023-01-19 00:52:41,106 DEBUG main GTK Version: 3.24.33
----------------------------------------------------------------------
2023-01-19 00:52:41,106 DEBUG main Is the system already running GTK? false
----------------------------------------------------------------------
2023-01-19 00:52:41,147 DEBUG main Loaded GTK3 library name 'appindicator3'.
----------------------------------------------------------------------
2023-01-19 00:52:41,221 DEBUG main Tray indicator image size: 24
----------------------------------------------------------------------
2023-01-19 00:52:41,221 DEBUG main Tray menu image size: 16
----------------------------------------------------------------------
2023-01-19 00:52:41,233 DEBUG main Using Fake CheckMark: false
----------------------------------------------------------------------
2023-01-19 00:52:41,340 INFO  main Successfully loaded type: _AppIndicatorNativeTray
----------------------------------------------------------------------
2023-01-19 00:52:41,341 WARN  main Please disable tooltips, as they are not consistent across all platforms and tray types.
----------------------------------------------------------------------
2023-01-19 00:52:41,341 DEBUG main Resizing image to 24 : file:/.../tray-icon.png
----------------------------------------------------------------------
2023-01-19 00:52:41,354 INFO  main Started system tray
```

**Comment by theangrydev** [comment]
This is where it seems to get stuck:
```
"main@1" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:460)
	  at java.util.concurrent.TimeUnit.timedWait(TimeUnit.java:348)
	  at java.lang.UNIXProcess.waitFor(UNIXProcess.java:410)
	  at dorkbox.os.OS.execute(OS.kt:450)
	  at dorkbox.os.OS.execute$default(OS.kt:445)
	  at dorkbox.os.OS$DesktopEnv$isGnome$2.invoke(OS.kt:979)
	  at dorkbox.os.OS$DesktopEnv$isGnome$2.invoke(OS.kt:970)
	  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	  - locked <0x2931> (a kotlin.SynchronizedLazyImpl)
	  at dorkbox.os.OS$DesktopEnv.isGnome(OS.kt:970)
	  at dorkbox.os.OS$DesktopEnv$env$2.invoke(OS.kt:1192)
	  at dorkbox.os.OS$DesktopEnv$env$2.invoke(OS.kt:1176)
	  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	  - locked <0x2932> (a kotlin.SynchronizedLazyImpl)
	  at dorkbox.os.OS$DesktopEnv.getEnv(OS.kt:1176)
	  at dorkbox.os.OS$DesktopEnv.<clinit>(OS.kt:1229)
	  at dorkbox.systemTray.util.AutoDetectTrayType.get(AutoDetectTrayType.java:133)
	  at dorkbox.systemTray.SystemTray.get(SystemTray.java:541)
	  - locked <0x268e> (a java.lang.Class)
	  at dorkbox.systemTray.SystemTray.get(SystemTray.java:171)

```

**Comment by theangrydev** [comment]
Which is apparently:
```
var contains = execute("ps", "x").contains("gnome-shell")
```

Timing out after 60 seconds

If I execute this on a terminal I get an instant response:
```
$ ps x | grep gnome-shell
   4300 ?        Ssl   11:35 /usr/bin/gnome-shell
   4354 ?        Sl     0:00 /usr/libexec/gnome-shell-calendar-server
   4414 ?        Sl     0:00 /usr/bin/gjs /usr/share/gnome-shell/org.gnome.Shell.Notifications
   4644 ?        Sl     0:00 /usr/bin/gjs /usr/share/gnome-shell/org.gnome.ScreenSaver
   4802 ?        Sl     0:04 gjs /usr/share/gnome-shell/extensions/ding@rastersoft.com/ding.js -E -P /usr/share/gnome-shell/extensions/ding@rastersoft.com -M 0 -D 0:0:1920:1080:1:27:0:74:0:0
  35485 pts/2    S+     0:00 grep --color=auto gnome-shell
```

**Comment by theangrydev** [comment]
The jpms vs non-jpms JAR suspicion is a red herring, I see the same behaviour with either

**Comment by dorkbox** [comment]
Oh! Good find. I'll look into that!

**Comment by theangrydev** [comment]
Any ETA on this? Were you able to investigate the cause yet?

**Comment by dorkbox** [comment]
I had GitHub notifications going to spam, so I completely missed these. I’m looking at it now.

**Comment by dorkbox** [comment]
This is working in the pre-release — I’ve added absolute paths for these commands, as the only thing I can think of is that this is operating in an environement where the path is not configured.
